<?php

namespace AppBundle\Repository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends \Doctrine\ORM\EntityRepository
{
    public function simpleSearch($searched)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->where('a.nom LIKE :searched')
            ->setParameter('searched', '%'.$searched.'%')
        ;
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function authorsList ($letter = null){
        $qb = $this
            ->createQueryBuilder('a')
            ->orderBy('a.nom' , 'ASC')
        ;
        if ($letter){
            $qb->where('a.nom LIKE :letter')
                ->setParameter('letter', $letter.'%')
            ;
        }
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

}
