<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Author;

/**
 * AuthorBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorBookRepository extends \Doctrine\ORM\EntityRepository
{
    public function simpleSearch($searched)
    {
        $qb = $this
            ->createQueryBuilder('ab')
            ->join('ab.author', 'a')
            ->join('ab.book', 'b')
            ->where('b.titre LIKE :searched')
            ->orWhere('b.isbn LIKE :searched')
            ->orWhere('a.nom LIKE :searched')
            ->setParameter('searched', '%'.$searched.'%')
        ;
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }


}
