<?php

namespace AppBundle\Repository;

/**
 * AuthorBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorBookRepository extends \Doctrine\ORM\EntityRepository
{
}
