<?php

namespace AppBundle\Repository;

/**
 * CategoryBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryBookRepository extends \Doctrine\ORM\EntityRepository
{
}
