<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;


/**
 * LibraryBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibraryBookRepository extends \Doctrine\ORM\EntityRepository
{
    public function exchangeList(User $user = null)
    {
        $qb = $this
            ->createQueryBuilder('lb')
            ->where('lb.exchange = true')
        ;
        if ($user){
            $qb->andWhere('lb.user <> :user')
                ->setParameter('user',$user)
            ;
        }
        $qb->orderBy('lb.dateAjout','ASC');
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function giveawayList(User $user = null)
    {
        $qb = $this
            ->createQueryBuilder('lb')
            ->where('lb.giveaway = true')
        ;
        if ($user){
            $qb->andWhere('lb.user <> :user')
                ->setParameter('user',$user)
            ;
        }
        $qb->orderBy('lb.dateAjout','ASC');
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function sellList(User $user = null)
    {
        $qb = $this
            ->createQueryBuilder('lb')
            ->where('lb.sell = true')
        ;
        if ($user){
            $qb->andWhere('lb.user <> :user')
                ->setParameter('user',$user)
            ;
        }
        $qb->orderBy('lb.dateAjout','ASC');
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

}
