<?php

namespace AppBundle\Repository;

/**
 * LibraryBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibraryBookRepository extends \Doctrine\ORM\EntityRepository
{
}
