<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Book;
use AppBundle\Entity\User;
use Symfony\Component\Security\Csrf\TokenStorage\TokenStorageInterface;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{
//    private $user;
//
//    /**
//     * ReviewRepository constructor.
//     * @param TokenStorageInterface $tokenStorage
//     */
//    public function __construct( TokenStorageInterface $tokenStorage)
//    {
//        $this->user = $tokenStorage->getToken()->getUser();
//    }


    public function bookReviewsList(Book $book )
    {

        $qb = $this
            ->createQueryBuilder('r')
            ->where('r.book = :book')
            ->setParameter('book',$book)

        ;
        $qb->orderBy('r.createdAt','DESC');
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function latestReviews($limit){
        $qb = $this
            ->createQueryBuilder('r')
            ->orderBy('r.createdAt', 'DESC')
            ->setMaxResults($limit)
        ;
        $qb->orderBy('r.createdAt','DESC');
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
