<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Book;
use AppBundle\Entity\User;
use Symfony\Component\Security\Csrf\TokenStorage\TokenStorageInterface;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{
//    private $user;
//
//    /**
//     * ReviewRepository constructor.
//     * @param TokenStorageInterface $tokenStorage
//     */
//    public function __construct( TokenStorageInterface $tokenStorage)
//    {
//        $this->user = $tokenStorage->getToken()->getUser();
//    }


    public function bookReviewsList(Book $book , User $user = null)
    {

        $qb = $this
            ->createQueryBuilder('r')
            ->where('r.book = :book')
            ->setParameter('book',$book)

        ;
        if ($user){
            $qb->andWhere('r.user <> :user')
                ->setParameter('user',$user)
            ;
        }
        $qb->orderBy('r.createdAt','DESC');
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
